INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Mercedes-Benz', 40000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Pz4V Tiger 1', 100000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Maus', 1540000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('East Carpet', 300);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Compass', 50);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Tabaco', 500);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Paper', 100);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Gunpowder', 100);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Papirus', 300);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Old Rome Wine', 1000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Golden Bricks', 50000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Building Cobblestone', 10);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Oil', 20);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Copper wires (100 m)', 15);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Iron sword', 50);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('War horse', 200);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Bomb', 1500);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Leiden Battery', 250);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Coil', 30);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Wood', 25);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('OS Windows', 1500);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('iPhone XS', 20000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('iMac', 50000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Chair', 5);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Metal', 20);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Electric Chair', 3000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Tazik-Evtanazik', 666);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('BattleShip', 5000000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Yacht', 80000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Caravel', 200000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Canon', 1000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Sugar', 40);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Pistol', 100);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Shotgun', 500);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Diamond', 777000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Spices', 4000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Medicines', 5000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Surgery Kit', 10000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Painkiller', 3000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Indulgence', 321000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Christening', 969696);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Weed', 333);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Golden Bricks', 500000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Bow', 250);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Arrow', 2);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Crusade(Palestina)', 8800000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Crusade(Jerusalem)', 15000000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Tesla Coil', 101010);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Letter of marque', 90000);
INSERT INTO Goods (Goods_Name, Goods_Price) VALUES ('Watches', 333);