INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (10, '2019-01-06', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES ( 9, '2019-01-07', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (10, '2019-01-08', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (15, '2019-01-09', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (10, '2019-01-10', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (13, '2019-01-12', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (14, '2019-01-12', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES ( 9, '2019-01-17', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (16, '2019-01-19', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (13, '2019-01-21', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (12, '2019-01-23', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES ( 8, '2019-01-25', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (13, '2019-01-25', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (10, '2019-01-29', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (11, '2019-01-29', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (15, '2019-01-31', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (11, '2019-02-01', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (16, '2019-02-07', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (10, '2019-02-10', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (16, '2019-02-15', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (13, '2019-02-16', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (15, '2019-02-19', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES ( 8, '2019-02-19', 'bla-bla-bla');
INSERT INTO ExportDocument (Document_CustomerID, Document_ExportDate, Document_Description) VALUES (15, '2019-02-21', 'bla-bla-bla');