INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES ( 1, 4);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES ( 2, 2);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES ( 3, 3);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES ( 4, 1);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES ( 5, 3);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES ( 6, 2);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES ( 7, 4);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES ( 8, 2);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES ( 9, 1);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (10, 2);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (11, 4);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (12, 2);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (13, 4);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (14, 3);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (15, 3);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (16, 1);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (17, 2);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (18, 2);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (19, 3);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (20, 2);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (21, 2);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (22, 2);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (23, 4);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (24, 2);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (25, 3);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (26, 2);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (27, 1);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (28, 4);
INSERT INTO ExportMoveDocument (Document_ExportGoodsID, Document_StorageID) VALUES (29, 1);