INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 1, '2019-01-01', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 2, '2019-01-02', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 4, '2019-01-02', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 9, '2019-01-03', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 3, '2019-01-03', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 9, '2019-01-03', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 7, '2019-01-06', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 2, '2019-01-07', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (12, '2019-01-07', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 6, '2019-01-07', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 3, '2019-01-08', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (11, '2019-01-09', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 5, '2019-01-13', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 6, '2019-01-16', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (16, '2019-01-16', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 4, '2019-01-17', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 9, '2019-01-18', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (10, '2019-01-19', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 9, '2019-01-20', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 3, '2019-01-20', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (15, '2019-01-21', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 8, '2019-01-22', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 4, '2019-01-23', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 7, '2019-01-25', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (16, '2019-01-26', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (11, '2019-01-26', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (13, '2019-01-28', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (10, '2019-01-30', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (15, '2019-02-01', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 4, '2019-02-01', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 8, '2019-02-03', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (10, '2019-02-03', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (14, '2019-02-03', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 7, '2019-02-06', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (15, '2019-02-06', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (13, '2019-02-07', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (14, '2019-02-10', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES ( 3, '2019-02-10', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (16, '2019-02-11', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (13, '2019-02-11', 'bla-bla-bla');
INSERT INTO ImportDocument (Document_ProviderID, Document_ImportDate, Document_Description) VALUES (12, '2019-02-15', 'bla-bla-bla');