INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('Damler-Benz', 'Germany', 'Company, which creates a lot of machines.');
INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('Maybach', 'Germany', 'Company, which creates a lot of tanks and crazy machines.');
INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('East India Company', 'UK', 'Very rich people of New Time Period.');
INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('FaradayWorkshop', 'UK', 'Shop of electric goods.');
INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('Microsoft', 'USA', 'Evil company, which created MustDie Windows.');
INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('Apple', 'USA', 'Evil snob company, which like a loot of Ponthy');
INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('IKEA', 'Netherlands', 'Just provide chairs.');
INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('Winchester', 'USA', 'Gun company and Supernatural heroes.');
INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('RomeEmpire', 'Italia', 'Si vis pacem, para bellum.');
INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('KnigthCompany', 'UK', 'Ave Maria! Deus Vult!');
INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('Alkaida', 'Afghanistan', 'Allahu akbar!');
INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('National Mining Comp', 'USA', 'We can mine all things that you need.');
INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('Pirate Society', 'Spain', 'Ahrrr! Abourdage!');
INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('Oxford Medical', 'UK', 'We can cure almost everything.');
INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('Catholic Church', 'Italia', 'Amen!');
INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('Brotherhood of Nod', 'USA', 'Kane will live forever!');
INSERT INTO Provider (Provider_Name, Provider_Country, Provider_Description) VALUES ('Snoop Dog', 'USA', 'Smoke weed every day!');

INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('Damler-Benz', 'Germany', 'Company, which creates a lot of machines.');
INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('Maybach', 'Germany', 'Company, which creates a lot of tanks and crazy machines.');
INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('East India Company', 'UK', 'Very rich people of New Time Period.');
INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('FaradayWorkshop', 'UK', 'Shop of electric goods.');
INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('Microsoft', 'USA', 'Evil company, which created MustDie Windows.');
INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('Apple', 'USA', 'Evil snob company, which like a loot of Ponthy');
INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('IKEA', 'Netherlands', 'Just provide chairs.');
INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('Winchester', 'USA', 'Gun company and Supernatural heroes.');
INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('RomeEmpire', 'Italia', 'Si vis pacem, para bellum.');
INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('KnigthCompany', 'UK', 'Ave Maria! Deus Vult!');
INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('Alkaida', 'Afghanistan', 'Allahu akbar!');
INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('National Mining Comp', 'USA', 'We can mine all things that you need.');
INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('Pirate Society', 'Spain', 'Ahrrr! Abourdage!');
INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('Oxford Medical', 'UK', 'We can cure almost everything.');
INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('Catholic Church', 'Italia', 'Amen!');
INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('Brotherhood of Nod', 'USA', 'Kane will live forever!');
INSERT INTO Customer (Customer_Name, Customer_Country, Customer_Description) VALUES ('Snoop Dog', 'USA', 'Smoke weed every day!');

