INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES ( 1, 1);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES ( 2, 1);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES ( 3, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES ( 4, 4);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES ( 5, 4);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES ( 6, 3);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES ( 7, 3);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES ( 8, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES ( 9, 1);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (10, 4);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (11, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (12, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (13, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (14, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (15, 4);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (16, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (17, 4);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (18, 4);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (19, 3);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (20, 1);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (21, 4);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (22, 4);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (23, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (24, 3);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (25, 3);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (26, 3);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (27, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (28, 3);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (29, 4);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (30, 1);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (31, 1);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (32, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (33, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (34, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (35, 3);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (36, 1);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (37, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (38, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (39, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (40, 3);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (41, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (42, 1);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (43, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (44, 4);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (45, 2);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (46, 1);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (47, 3);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (48, 4);
INSERT INTO ImportMoveDocument (Document_ImportGoodsID, Document_StorageID) VALUES (49, 4);