INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Mercedes-Benz',         40000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Pz4V Tiger 1',         100000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Maus',                2700000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('East Carpet',             300);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Compass',                 250);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Tabaco',                  500);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Paper',                   100);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Gunpowder',               500);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Papirus',                 300);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Old Rome Wine',          1000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Golden Bricks',         50000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Building Cobblestone',     80);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Oil',                      20);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Copper wires (100 m)',     15);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Iron sword',               50);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('War horse',             12000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Bomb',                   1500);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Leiden Battery',          250);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Coil',                     30);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Wood',                     25);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('OS Windows',             1500);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('iPhone XS',             20000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('iMac',                  20000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Chair',                     5);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Metal',                    40);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Electric Chair',         3000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Tazik-Evtanazik',         666);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('BattleShip',          5000000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Yacht',                 80000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Caravel',               40000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Canon',                  1000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Sugar',                   400);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Pistol',                  100);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Shotgun',                 500);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Diamond',              777000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Spices',                 4000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Medicines',               500);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Surgery Kit',            5000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Painkiller',              100);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Indulgence',              400);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Christening',          969696);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Weed',                   1500);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Bow',                      20);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Arrow',                     2);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Crusade(Palestina)',  8800000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Crusade(Jerusalem)', 15000000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Tesla Coil',           101010);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Letter of marque',      90000);
INSERT INTO Goods (Goods_Name, Goods_Average_Price) VALUES ('Watches',                2000);