INSERT INTO Provider (Provider_Name) VALUES ('Damler-Benz');
INSERT INTO Provider (Provider_Name) VALUES ('Maybach');
INSERT INTO Provider (Provider_Name) VALUES ('East India Company');
INSERT INTO Provider (Provider_Name) VALUES ('FaradayWorkshop');
INSERT INTO Provider (Provider_Name) VALUES ('Microsoft');
INSERT INTO Provider (Provider_Name) VALUES ('Apple');
INSERT INTO Provider (Provider_Name) VALUES ('IKEA');
INSERT INTO Provider (Provider_Name) VALUES ('Winchester');
INSERT INTO Provider (Provider_Name) VALUES ('RomeEmpire');
INSERT INTO Provider (Provider_Name) VALUES ('KnigthCompany');
INSERT INTO Provider (Provider_Name) VALUES ('Alkaida');
INSERT INTO Provider (Provider_Name) VALUES ('National Mining Comp');
INSERT INTO Provider (Provider_Name) VALUES ('Pirate Society');
INSERT INTO Provider (Provider_Name) VALUES ('Oxford Medical');
INSERT INTO Provider (Provider_Name) VALUES ('Catholic Church');
INSERT INTO Provider (Provider_Name) VALUES ('Brotherhood of Nod');
INSERT INTO Provider (Provider_Name) VALUES ('Snoop Dog');

INSERT INTO Customer (Customer_Name) VALUES ('Damler-Benz');
INSERT INTO Customer (Customer_Name) VALUES ('Maybach');
INSERT INTO Customer (Customer_Name) VALUES ('East India Company');
INSERT INTO Customer (Customer_Name) VALUES ('FaradayWorkshop');
INSERT INTO Customer (Customer_Name) VALUES ('Microsoft');
INSERT INTO Customer (Customer_Name) VALUES ('Apple');
INSERT INTO Customer (Customer_Name) VALUES ('IKEA');
INSERT INTO Customer (Customer_Name) VALUES ('Winchester');
INSERT INTO Customer (Customer_Name) VALUES ('RomeEmpire');
INSERT INTO Customer (Customer_Name) VALUES ('KnigthCompany');
INSERT INTO Customer (Customer_Name) VALUES ('Alkaida');
INSERT INTO Customer (Customer_Name) VALUES ('National Mining Comp');
INSERT INTO Customer (Customer_Name) VALUES ('Pirate Society');
INSERT INTO Customer (Customer_Name) VALUES ('Oxford Medical');
INSERT INTO Customer (Customer_Name) VALUES ('Catholic Church');
INSERT INTO Customer (Customer_Name) VALUES ('Brotherhood of Nod');
INSERT INTO Customer (Customer_Name) VALUES ('Snoop Dog');

